name: CoinsEngine
version: '${project.version}'
main: su.nightexpress.coinsengine.CoinsEnginePlugin
api-version: '1.21'
folia-supported: true
load: STARTUP
dependencies:
  server:
    nightcore:
      load: BEFORE
      required: true
    Vault:
      required: false
    PlaceholderAPI:
      required: false
    PlayerPoints:
      required: false
    DeluxeCoinflip:
      required: false
  bootstrap:
    - name: nightcore
      required: true
description: Unlimited virtual currencies and server economy.
authors:
  - NightExpress
